
services:
  postgres_con:
    image: postgres:15
    container_name: postgres_con
    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: "VidVault"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my-network

  vidvault_con:
    depends_on:
      - postgres_con
#    image: ritikkumar352/vidvault_img
    build: . # Build from the cloned GitHub repo instead if pull from DockerHub
    container_name: vidvault_con
    ports:
      - "443:443"
#      - "8080:8080"
    volumes:
      - ./config/videoupload-453311-0748888572ad.json:/app/config/videoupload-453311-0748888572ad.json  # Mount the JSON file
      - ./src/main/resources:/app/resources
      - ./config/origin.crt:/etc/ssl/cloudflare/origin.crt  # to mount SSL cert
      - ./config/origin.key:/etc/ssl/cloudflare/origin.key  # to mount SSL key
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/app/config/videoupload-453311-0748888572ad.json"  # Set the env variable
    networks:
      - my-network


networks:
  my-network:
    name: my-network

